### ISSUE TITLE
[BUG]: Kernel crash on WLANPi Go when transferring USB accessory data.

### ISSUE THREAD

**Issue by Tekrad** [WLAN-Pi/wlanpi-kernel#14]
### What happened?

Kernel crash on WLANPi Go when transferring USB accessory data.

### Relevant log output

```shell
NA
```

### How often does this bug happen?

Every time

### What version are you using?

6.12.1

### Self Service

- [X] I would be willing to fix this bug myself.

### Guidelines and Policies

- [X] I have read the contributing guidelines and agree to follow the code of conduct and contribution policies.

**Comment by Tekrad** [comment]
Fix identified and kernel patch created.  This can be applied to any kernel after Linux-6.2.x

**Comment by joshschmelzle** [comment]
Closed by 6628d61 in #16
