### ISSUE TITLE
Package the latest iwlwifi Intel Wi-Fi + BT firmware

### ISSUE THREAD

**Issue by jiribrejcha** [WLAN-Pi/wlanpi-kernel#2]
This is a suggestion to package the latest iwlwifi Intel Wi-Fi + Bluetooth firmware and install them as a Debian package.

Daniel suggested **wlanpi-firmware-iwlwifi** or **wlanpi-firmware-wlan** as a package name.

```
wget https://git.kernel.org/pub/scm/linux/kernel/git/iwlwifi/linux-firmware.git/snapshot/linux-firmware-iwlwifi-fw-2022-01-11.tar.gz
tar -xf linux-firmware-iwlwifi-fw-2022-01-11.tar.gz
cd linux
sudo cp iwlwifi-*.ucode /lib/firmware
```

**Comment by jolla** [comment]
The latest iwlwifi firmware now gets installed with package wlanpi-linux-firmware
